# Generated by Django 3.2 on 2021-08-24 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=1000)),
                ('num_analyses', models.IntegerField(default=0)),
                ('num_videos', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(default='Nothing', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(default='Nothing', upload_to='videos/')),
                ('client', models.ForeignKey(default='Nothing', on_delete=django.db.models.deletion.CASCADE, to='page.client')),
            ],
        ),
    ]
