# Generated by Django 3.2 on 2021-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='num_analyses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=4),
        ),
    ]
