# Generated by Django 3.2 on 2021-08-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_video_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='page.client'),
        ),
    ]
