# Generated by Django 3.2 on 2021-05-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='title',
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.CharField(max_length=1000),
        ),
    ]
