# Generated by Django 3.2 on 2021-05-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210519_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dob',
            new_name='notes',
        ),
    ]
