# Generated by Django 3.2 on 2021-08-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_video_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.FileField(default='profile_pics/default.jpg', upload_to=''),
        ),
    ]
