# Generated by Django 3.2 on 2021-07-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_rename_dob_client_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=500),
        ),
    ]
