# Generated by Django 3.2 on 2021-07-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_video_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='../../media/videos/'),
        ),
    ]
