# Generated by Django 3.2 on 2021-09-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_rename_client_video_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
    ]
