# Generated by Django 3.2 on 2021-09-14 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
