# Generated by Django 3.2 on 2021-09-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_video_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='Nothing', upload_to='videos/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
