# Generated by Django 3.2 on 2021-07-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='title',
        ),
    ]
