# Generated by Django 3.2 on 2021-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
