# Generated by Django 3.2 on 2021-07-29 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0011_rename_caption_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='Nothing', upload_to='videos/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
