# Generated by Django 3.2 on 2021-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='Nothing', upload_to='videos/<property object at 0x0000015A66F75A40>'),
        ),
    ]
