# Generated by Django 3.2 on 2021-09-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_alter_client_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='user_id',
        ),
    ]
