# Generated by Django 3.2 on 2021-09-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_rename_client_id_client_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
    ]
