# Generated by Django 3.2 on 2021-07-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='Nothing', upload_to='videos/'),
        ),
    ]
