# Generated by Django 3.2 on 2021-09-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20210914_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis',
            field=models.FilePathField(default='No Analysis'),
        ),
    ]
