# Generated by Django 3.2 on 2021-09-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_video_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
