# Generated by Django 3.2 on 2021-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_video_analysis_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='analysis_title',
            field=models.CharField(default='Analysis Title', max_length=100),
        ),
    ]
