# Generated by Django 3.2 on 2021-09-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_alter_video_analysis_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='analysis_title',
        ),
    ]
