# Generated by Django 3.2 on 2021-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_remove_video_analysis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_title',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
