# Generated by Django 3.2 on 2021-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0026_alter_video_analysis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='skeleton_video',
            field=models.FilePathField(default='Nothing'),
        ),
    ]
