# Generated by Django 3.2 on 2021-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_video_skeleton_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='skeleton_video',
            field=models.FileField(default='Nothing', upload_to=''),
        ),
    ]
